version: '3.3'

services:
#  server:
#    image: kali_ue:latest
#    ports:
#      - "8081:80"
#    networks:
#      privnet:
#        aliases:
#          - server1.org

  free5gc-upf:
    container_name: upf
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - upf.free5gc.org

  free5gc-upf2:
    container_name: upf2
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg2.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - upf2.free5gc.org

  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "false"
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "false"
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "false"
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "false"
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "false"
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf
      - free5gc-upf2

  free5gc-smf2:
    container_name: smf2
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg2.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting2.yaml:/free5gc/config/uerouting.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf2.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf
      - free5gc-upf2

  free5gc-udm:
    container_name: udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "false"
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "false"
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-n3iwf:
    container_name: n3iwf
    build:
      context: ./nf_n3iwf
      args:
        DEBUG_TOOLS: "false"
    command: sh -c "./n3iwf-ipsec.sh && ./n3iwf -c ./config/n3iwfcfg.yaml"
    volumes:
      - ./config/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - ./config/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - n3iwf.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-smf
      - free5gc-smf2
      - free5gc-upf
      - free5gc-upf2

  free5gc-webui:
    container_name: webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "false"
    command: ./webui -c ./config/webuicfg.yaml
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      privnet:
        aliases:
          - webui
    ports:
      - "5000:5000"
    depends_on:
      - db

  ueransim:
    container_name: ueransim
    build:
      context: ./ueransim
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue1_cfg.yaml:/ueransim/config/ue1_cfg.yaml
#      - ./config/ue_cfg/ue3_cfg.yaml:/ueransim/config/ue3_cfg.yaml
#      - ./config/ue_cfg/ue5_cfg.yaml:/ueransim/config/ue5_cfg.yaml
#      - ./config/ue_cfg/ue7_cfg.yaml:/ueransim/config/ue7_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - free5gc-upf2


  ue1:
    container_name: ue1
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue1_cfg.yaml
    volumes:
#      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/ue_cfg/ue1_cfg.yaml:/ueransim/config/ue1_cfg.yaml
#      - ./config/ue_cfg/ue3_cfg.yaml:/ueransim/config/ue3_cfg.yaml
#      - ./config/ue_cfg/ue5_cfg.yaml:/ueransim/config/ue5_cfg.yaml
#      - ./config/ue_cfg/ue7_cfg.yaml:/ueransim/config/ue7_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue1.free5gc.org
    depends_on:
      - ueransim
      - free5gc-amf
      - free5gc-upf

  ue3:
    container_name: ue3
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue3_cfg.yaml
    volumes:
#      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue1_cfg.yaml:/ueransim/config/ue1_cfg.yaml
      - ./config/ue_cfg/ue3_cfg.yaml:/ueransim/config/ue3_cfg.yaml
#      - ./config/ue_cfg/ue5_cfg.yaml:/ueransim/config/ue5_cfg.yaml
#      - ./config/ue_cfg/ue7_cfg.yaml:/ueransim/config/ue7_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue3.free5gc.org
    depends_on:
      - ueransim
      - free5gc-amf
      - free5gc-upf

  ue5:
    container_name: ue5
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue5_cfg.yaml
    volumes:
#      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue1_cfg.yaml:/ueransim/config/ue1_cfg.yaml
#      - ./config/ue_cfg/ue3_cfg.yaml:/ueransim/config/ue3_cfg.yaml
      - ./config/ue_cfg/ue5_cfg.yaml:/ueransim/config/ue5_cfg.yaml
#      - ./config/ue_cfg/ue7_cfg.yaml:/ueransim/config/ue7_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue5.free5gc.org
    depends_on:
      - ueransim
      - free5gc-amf
      - free5gc-upf


  ue7:
    container_name: ue7
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue7_cfg.yaml
    volumes:
#      - ./config/gnbcfg.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue1_cfg.yaml:/ueransim/config/ue1_cfg.yaml
#      - ./config/ue_cfg/ue3_cfg.yaml:/ueransim/config/ue3_cfg.yaml
#      - ./config/ue_cfg/ue5_cfg.yaml:/ueransim/config/ue5_cfg.yaml
      - ./config/ue_cfg/ue7_cfg.yaml:/ueransim/config/ue7_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue7.free5gc.org
    depends_on:
      - ueransim
      - free5gc-amf
      - free5gc-upf

  ueransim2:
    container_name: ueransim2
    build:
      context: ./ueransim
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue2_cfg.yaml:/ueransim/config/ue2_cfg.yaml
#      - ./config/ue_cfg/ue4_cfg.yaml:/ueransim/config/ue4_cfg.yaml
#      - ./config/ue_cfg/ue6_cfg.yaml:/ueransim/config/ue6_cfg.yaml
#      - ./config/ue_cfg/ue8_cfg.yaml:/ueransim/config/ue8_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - gnb2.free5gc.org
    depends_on:
      - free5gc-amf
      - free5gc-upf
      - free5gc-upf2


  ue2:
    container_name: ue2
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue2_cfg.yaml
    volumes:
#      - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/ue_cfg/ue2_cfg.yaml:/ueransim/config/ue2_cfg.yaml
#      - ./config/ue_cfg/ue4_cfg.yaml:/ueransim/config/ue4_cfg.yaml
#      - ./config/ue_cfg/ue6_cfg.yaml:/ueransim/config/ue6_cfg.yaml
#      - ./config/ue_cfg/ue8_cfg.yaml:/ueransim/config/ue8_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue2.free5gc.org
    depends_on:
      - ueransim2
      - free5gc-amf
      - free5gc-upf2


  ue4:
    container_name: ue4
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue4_cfg.yaml
    volumes:
#      - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue2_cfg.yaml:/ueransim/config/ue2_cfg.yaml
      - ./config/ue_cfg/ue4_cfg.yaml:/ueransim/config/ue4_cfg.yaml
#      - ./config/ue_cfg/ue6_cfg.yaml:/ueransim/config/ue6_cfg.yaml
#      - ./config/ue_cfg/ue8_cfg.yaml:/ueransim/config/ue8_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue4.free5gc.org
    depends_on:
      - ueransim2
      - free5gc-amf
      - free5gc-upf2


  ue6:
    container_name: ue6
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue6_cfg.yaml
    volumes:
#      - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue2_cfg.yaml:/ueransim/config/ue2_cfg.yaml
#      - ./config/ue_cfg/ue4_cfg.yaml:/ueransim/config/ue4_cfg.yaml
      - ./config/ue_cfg/ue6_cfg.yaml:/ueransim/config/ue6_cfg.yaml
#      - ./config/ue_cfg/ue8_cfg.yaml:/ueransim/config/ue8_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue6.free5gc.org
    depends_on:
      - ueransim2
      - free5gc-amf
      - free5gc-upf2


  ue8:
    container_name: ue8
    build:
      context: ./ueransim
    command: ./nr-ue -c ./config/ue8_cfg.yaml
    volumes:
#      - ./config/gnbcfg2.yaml:/ueransim/config/gnbcfg.yaml
#      - ./config/ue_cfg/ue2_cfg.yaml:/ueransim/config/ue2_cfg.yaml
#      - ./config/ue_cfg/ue4_cfg.yaml:/ueransim/config/ue4_cfg.yaml
#      - ./config/ue_cfg/ue6_cfg.yaml:/ueransim/config/ue6_cfg.yaml
      - ./config/ue_cfg/ue8_cfg.yaml:/ueransim/config/ue8_cfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        aliases:
          - ue8.free5gc.org
    depends_on:
      - ueransim2
      - free5gc-amf
      - free5gc-upf2

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
